import Head from "next/head";
import Image from "next/image";
import { AiFillGithub } from "react-icons/ai";
import { BsTwitter, BsGoogle } from "react-icons/bs";
import { useSession, signIn, signOut } from "next-auth/react";
import { useRouter } from "next/router";

export default function Home() {
  const { data: session } = useSession();
  const router = useRouter();
  const handleSignOut = async () => {
    const { url } = await signOut({
      redirect: false,
      callbackUrl: "/redirect",
    });
    router.push(url);
  };

  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        {/* <button rel="icon" href="/favicon.ico" /> */}
      </Head>

      <div className="min-h-[100vh] bg-gray-100 flex items-center justify-center flex-col gap-6">
        {session ? (
          <h1 className="text-lg">
            You are now logged in as{" "}
            <span className="text-2xl text-green-600">
              {session.user.email}
            </span>
          </h1>
        ) : (
          <h1 className="text-lg">You are not logged in</h1>
        )}
        {!session && (
          <>
            <div>
              <p>or</p>
            </div>

            <div className="flex items-center gap-6">
              <button className="provider" onClick={() => signIn("github")}>
                <AiFillGithub className="icon" />
              </button>
              <button className="provider">
                <BsGoogle className="icon" />
              </button>
              <button className="provider">
                <BsTwitter className="icon" />
              </button>
            </div>
          </>
        )}
      </div>
      {session && (
        <button
          className="absolute bottom-[10%] left-[50%] translate-x-[-50%] bg-blue-600 capitalize px-4 py-2 text-white rounded-md shadow-lg"
          onClick={handleSignOut}
        >
          sign out
        </button>
      )}
    </div>
  );
}
